import { Template, waitForURL } from 'e2b'

export const template = Template()
  .fromNodeImage('22')
  .runCmd('npm install -g pnpm@11.0.9 --prefix /home/user/.local')
  .setWorkdir('/home/user/nextjs-app')
  .runCmd('/home/user/.local/bin/pnpm dlx create-next-app@latest . --app --ts --tailwind --yes --use-pnpm')
  .runCmd('/home/user/.local/bin/pnpm dlx shadcn@latest init -d -y')
  .runCmd('/home/user/.local/bin/pnpm dlx shadcn@latest add -a -y')
  .runCmd(
    'bash -lc "shopt -s dotglob nullglob && mv /home/user/nextjs-app/* /home/user/ && rmdir /home/user/nextjs-app"'
  )
  .setWorkdir('/home/user')
  .runCmd(`cat > next.config.ts <<'EOF'
import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  allowedDevOrigins: ["*.e2b.app", "**.e2b.app", "*.e2b.dev", "**.e2b.dev"],
};

export default nextConfig;
EOF`)
  .runCmd(`cat > app/layout.tsx <<'EOF'
import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
EOF`)
  .setStartCmd('/home/user/.local/bin/pnpm next dev -H 0.0.0.0 -p 3000', waitForURL('http://localhost:3000'))
